/*
 * Application.java
 *
 * Created on 9 de abril de 2008, 20:36
 */

package spf;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.Timer;

/**
 * Ventana principal de la aplicacion.
 * @author  Sergio
 */
public class SpfApplication extends JFrame {
	private static String ResourcesPath = "";
	
    private Timer m_FpsTimer;
	private SpfUniverse m_Universe;

    /** 
	 * Constructor de SpfApplication.
	 */
    public SpfApplication() {
		try {
			ResourcesPath = getClass().getResource("/spf/resources/").toURI().getPath();
		} catch (URISyntaxException e) {
			JOptionPane.showMessageDialog(this, e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
			System.exit(-1);
		}
		JPopupMenu.setDefaultLightWeightPopupEnabled(false);
		initComponents();
		// center frame
		setLocationRelativeTo(null);
		new SpfSplashScreen(this).setVisible(true);

		m_Universe = new SpfUniverse();
		getContentPane().add(m_Universe.loadScene());
			
		setIconImage(new ImageIcon(ResourcesPath + "8ball.png").getImage());
    }
	
	/**
	 * Inicializa la aplicacion y comienza el juego.
	 */
	public void init() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setTitle("SPF (FPS = " + m_Universe.getFps() + ")");
            }
        };
        m_FpsTimer = new Timer(1000, taskPerformer);
		m_Universe.startGame();
	}

	// <editor-fold defaultstate="collapsed" desc="Accesors">
	
	/**
	 * @return Devuelve el camino al directorio de recursos.
	 */
	public static String getResourcesPath() {
		return ResourcesPath;
	}
	
	// </editor-fold>
    
    /* This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        checkBoxMenuItemFps = new javax.swing.JCheckBoxMenuItem();
        checkBoxMenuItemAntialiasing = new javax.swing.JCheckBoxMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billar 3D");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));

        menuArchivo.setMnemonic('a');
        menuArchivo.setText("Archivo");

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        menuBar.add(menuArchivo);

        menuVer.setMnemonic('v');
        menuVer.setText("Ver");

        checkBoxMenuItemFps.setText("Mostrar FPS");
        checkBoxMenuItemFps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMenuItemFpsActionPerformed(evt);
            }
        });
        menuVer.add(checkBoxMenuItemFps);

        checkBoxMenuItemAntialiasing.setText("Antialiasing");
        checkBoxMenuItemAntialiasing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMenuItemAntialiasingActionPerformed(evt);
            }
        });
        menuVer.add(checkBoxMenuItemAntialiasing);

        menuBar.add(menuVer);

        menuAyuda.setMnemonic('y');
        menuAyuda.setText("Ayuda");

        menuItemAcercaDe.setText("Acerca de SPF");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuItemAcercaDe);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    
    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed
        SpfAboutBox box = new SpfAboutBox(this, true);
		box.setLocationRelativeTo(null);
		box.setVisible(true);
    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void checkBoxMenuItemFpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMenuItemFpsActionPerformed
        if (checkBoxMenuItemFps.isSelected()) {
            m_FpsTimer.start();
            setTitle("SPF (FPS = 0)");
        } else {
            m_FpsTimer.stop();
            setTitle("SPF");
        }
    }//GEN-LAST:event_checkBoxMenuItemFpsActionPerformed

	private void checkBoxMenuItemAntialiasingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMenuItemAntialiasingActionPerformed
		m_Universe.toggleAntialiasing();
	}//GEN-LAST:event_checkBoxMenuItemAntialiasingActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Design variables">
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem checkBoxMenuItemAntialiasing;
    private javax.swing.JCheckBoxMenuItem checkBoxMenuItemFps;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuVer;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
}
